//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESMSV3_1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.esms.mobitel.lk/", ConfigurationName="ServiceReference1.EnterpriseSMSWS")]
    public interface EnterpriseSMSWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.serviceTestResponse serviceTest(ESMSV3_1.ServiceReference1.serviceTest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.serviceTestResponse> serviceTestAsync(ESMSV3_1.ServiceReference1.serviceTest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.createSessionResponse createSession(ESMSV3_1.ServiceReference1.createSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.createSessionResponse> createSessionAsync(ESMSV3_1.ServiceReference1.createSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESMSV3_1.ServiceReference1.renewSessionResponse renewSession(ESMSV3_1.ServiceReference1.renewSession request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.renewSessionResponse> renewSessionAsync(ESMSV3_1.ServiceReference1.renewSession request);
        
        // CODEGEN: Parameter 'session' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESMSV3_1.ServiceReference1.closeSessionResponse closeSession(ESMSV3_1.ServiceReference1.closeSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.closeSessionResponse> closeSessionAsync(ESMSV3_1.ServiceReference1.closeSession request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ESMSV3_1.ServiceReference1.isSessionResponse isSession(ESMSV3_1.ServiceReference1.isSession request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.isSessionResponse> isSessionAsync(ESMSV3_1.ServiceReference1.isSession request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.sendMessagesResponse sendMessages(ESMSV3_1.ServiceReference1.sendMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesResponse> sendMessagesAsync(ESMSV3_1.ServiceReference1.sendMessages request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse sendMessagesMultiLang(ESMSV3_1.ServiceReference1.sendMessagesMultiLang request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse> sendMessagesMultiLangAsync(ESMSV3_1.ServiceReference1.sendMessagesMultiLang request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse sendCampaignMessages(ESMSV3_1.ServiceReference1.sendCampaignMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse> sendCampaignMessagesAsync(ESMSV3_1.ServiceReference1.sendCampaignMessages request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse getMessagesFromShortcode(ESMSV3_1.ServiceReference1.getMessagesFromShortcode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse> getMessagesFromShortcodeAsync(ESMSV3_1.ServiceReference1.getMessagesFromShortcode request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse getMessagesFromLongNumber(ESMSV3_1.ServiceReference1.getMessagesFromLongNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse> getMessagesFromLongNumberAsync(ESMSV3_1.ServiceReference1.getMessagesFromLongNumber request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.getSentMessageReportsResponse getSentMessageReports(ESMSV3_1.ServiceReference1.getSentMessageReports request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getSentMessageReportsResponse> getSentMessageReportsAsync(ESMSV3_1.ServiceReference1.getSentMessageReports request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESMSV3_1.ServiceReference1.getDeliveryReportsResponse getDeliveryReports(ESMSV3_1.ServiceReference1.getDeliveryReports request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getDeliveryReportsResponse> getDeliveryReportsAsync(ESMSV3_1.ServiceReference1.getDeliveryReports request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long customerField;
        
        private bool customerFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerSpecified {
            get {
                return this.customerFieldSpecified;
            }
            set {
                this.customerFieldSpecified = value;
                this.RaisePropertyChanged("customerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class sentMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string messageField;
        
        private string recipientField;
        
        private string statusField;
        
        private string timeSentField;
        
        private string timeDeliveredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string timeSent {
            get {
                return this.timeSentField;
            }
            set {
                this.timeSentField = value;
                this.RaisePropertyChanged("timeSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string timeDelivered {
            get {
                return this.timeDeliveredField;
            }
            set {
                this.timeDeliveredField = value;
                this.RaisePropertyChanged("timeDelivered");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class smsCampaignMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private long messageIdField;
        
        private string[] recipientsField;
        
        private int retriesField;
        
        private int esmClassField;
        
        private string senderField;
        
        private int sequenceNumField;
        
        private int statusField;
        
        private string timeField;
        
        private string typeField;
        
        private user userField;
        
        private int messageTypeField;
        
        private bool messageTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int retries {
            get {
                return this.retriesField;
            }
            set {
                this.retriesField = value;
                this.RaisePropertyChanged("retries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int esmClass {
            get {
                return this.esmClassField;
            }
            set {
                this.esmClassField = value;
                this.RaisePropertyChanged("esmClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int sequenceNum {
            get {
                return this.sequenceNumField;
            }
            set {
                this.sequenceNumField = value;
                this.RaisePropertyChanged("sequenceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageTypeSpecified {
            get {
                return this.messageTypeFieldSpecified;
            }
            set {
                this.messageTypeFieldSpecified = value;
                this.RaisePropertyChanged("messageTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class smsMessageMultiLang : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private long messageIdField;
        
        private string[] recipientsField;
        
        private int retriesField;
        
        private string senderField;
        
        private int sequenceNumField;
        
        private int statusField;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private string typeField;
        
        private user userField;
        
        private int messageTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int retries {
            get {
                return this.retriesField;
            }
            set {
                this.retriesField = value;
                this.RaisePropertyChanged("retries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int sequenceNum {
            get {
                return this.sequenceNumField;
            }
            set {
                this.sequenceNumField = value;
                this.RaisePropertyChanged("sequenceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class smsMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private long messageIdField;
        
        private bool messageIdFieldSpecified;
        
        private string[] recipientsField;
        
        private int retriesField;
        
        private bool retriesFieldSpecified;
        
        private string senderField;
        
        private int sequenceNumField;
        
        private bool sequenceNumFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private string typeField;
        
        private user userField;
        
        private int messageTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageIdSpecified {
            get {
                return this.messageIdFieldSpecified;
            }
            set {
                this.messageIdFieldSpecified = value;
                this.RaisePropertyChanged("messageIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int retries {
            get {
                return this.retriesField;
            }
            set {
                this.retriesField = value;
                this.RaisePropertyChanged("retries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retriesSpecified {
            get {
                return this.retriesFieldSpecified;
            }
            set {
                this.retriesFieldSpecified = value;
                this.RaisePropertyChanged("retriesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int sequenceNum {
            get {
                return this.sequenceNumField;
            }
            set {
                this.sequenceNumField = value;
                this.RaisePropertyChanged("sequenceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequenceNumSpecified {
            get {
                return this.sequenceNumFieldSpecified;
            }
            set {
                this.sequenceNumFieldSpecified = value;
                this.RaisePropertyChanged("sequenceNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.esms.mobitel.lk/")]
    public partial class session : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private string sessionIdField;
        
        private long userField;
        
        private bool userFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
                this.RaisePropertyChanged("expiryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("isActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
                this.RaisePropertyChanged("isActiveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userSpecified {
            get {
                return this.userFieldSpecified;
            }
            set {
                this.userFieldSpecified = value;
                this.RaisePropertyChanged("userSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceTest", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class serviceTest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.user arg0;
        
        public serviceTest() {
        }
        
        public serviceTest(ESMSV3_1.ServiceReference1.user arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceTestResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class serviceTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public serviceTestResponse() {
        }
        
        public serviceTestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createSession", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class createSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.user user;
        
        public createSession() {
        }
        
        public createSession(ESMSV3_1.ServiceReference1.user user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createSessionResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class createSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session @return;
        
        public createSessionResponse() {
        }
        
        public createSessionResponse(ESMSV3_1.ServiceReference1.session @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="renewSession", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class renewSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        public renewSession() {
        }
        
        public renewSession(ESMSV3_1.ServiceReference1.session session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="renewSessionResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class renewSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        public renewSessionResponse() {
        }
        
        public renewSessionResponse(ESMSV3_1.ServiceReference1.session @return, string status) {
            this.@return = @return;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="closeSession", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class closeSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        public closeSession() {
        }
        
        public closeSession(ESMSV3_1.ServiceReference1.session session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="closeSessionResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class closeSessionResponse {
        
        public closeSessionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isSession", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class isSession {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        public isSession() {
        }
        
        public isSession(ESMSV3_1.ServiceReference1.session session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isSessionResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class isSessionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        public isSessionResponse() {
        }
        
        public isSessionResponse(bool @return, string status) {
            this.@return = @return;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessages", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsMessage smsMessage;
        
        public sendMessages() {
        }
        
        public sendMessages(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessage smsMessage) {
            this.session = session;
            this.smsMessage = smsMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagesResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendMessagesResponse() {
        }
        
        public sendMessagesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagesMultiLang", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendMessagesMultiLang {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsMessageMultiLang smsMessageMultiLang;
        
        public sendMessagesMultiLang() {
        }
        
        public sendMessagesMultiLang(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessageMultiLang smsMessageMultiLang) {
            this.session = session;
            this.smsMessageMultiLang = smsMessageMultiLang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagesMultiLangResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendMessagesMultiLangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendMessagesMultiLangResponse() {
        }
        
        public sendMessagesMultiLangResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCampaignMessages", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendCampaignMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsCampaignMessage smsCampaignMessage;
        
        public sendCampaignMessages() {
        }
        
        public sendCampaignMessages(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsCampaignMessage smsCampaignMessage) {
            this.session = session;
            this.smsCampaignMessage = smsCampaignMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCampaignMessagesResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class sendCampaignMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendCampaignMessagesResponse() {
        }
        
        public sendCampaignMessagesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesFromShortcode", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getMessagesFromShortcode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shortcode;
        
        public getMessagesFromShortcode() {
        }
        
        public getMessagesFromShortcode(ESMSV3_1.ServiceReference1.session session, string shortcode) {
            this.session = session;
            this.shortcode = shortcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesFromShortcodeResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getMessagesFromShortcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsMessage[] @return;
        
        public getMessagesFromShortcodeResponse() {
        }
        
        public getMessagesFromShortcodeResponse(ESMSV3_1.ServiceReference1.smsMessage[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesFromLongNumber", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getMessagesFromLongNumber {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string longNumber;
        
        public getMessagesFromLongNumber() {
        }
        
        public getMessagesFromLongNumber(ESMSV3_1.ServiceReference1.session session, string longNumber) {
            this.session = session;
            this.longNumber = longNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMessagesFromLongNumberResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getMessagesFromLongNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsMessage[] @return;
        
        public getMessagesFromLongNumberResponse() {
        }
        
        public getMessagesFromLongNumberResponse(ESMSV3_1.ServiceReference1.smsMessage[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSentMessageReports", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getSentMessageReports {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;
        
        public getSentMessageReports() {
        }
        
        public getSentMessageReports(ESMSV3_1.ServiceReference1.session session, string startDate, string endDate, string alias) {
            this.session = session;
            this.startDate = startDate;
            this.endDate = endDate;
            this.alias = alias;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSentMessageReportsResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getSentMessageReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.sentMessages[] @return;
        
        public getSentMessageReportsResponse() {
        }
        
        public getSentMessageReportsResponse(ESMSV3_1.ServiceReference1.sentMessages[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryReports", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getDeliveryReports {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.session session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string alias;
        
        public getDeliveryReports() {
        }
        
        public getDeliveryReports(ESMSV3_1.ServiceReference1.session session, string alias) {
            this.session = session;
            this.alias = alias;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeliveryReportsResponse", WrapperNamespace="http://ws.esms.mobitel.lk/", IsWrapped=true)]
    public partial class getDeliveryReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.esms.mobitel.lk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESMSV3_1.ServiceReference1.smsMessage[] @return;
        
        public getDeliveryReportsResponse() {
        }
        
        public getDeliveryReportsResponse(ESMSV3_1.ServiceReference1.smsMessage[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnterpriseSMSWSChannel : ESMSV3_1.ServiceReference1.EnterpriseSMSWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnterpriseSMSWSClient : System.ServiceModel.ClientBase<ESMSV3_1.ServiceReference1.EnterpriseSMSWS>, ESMSV3_1.ServiceReference1.EnterpriseSMSWS {
        
        public EnterpriseSMSWSClient() {
        }
        
        public EnterpriseSMSWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnterpriseSMSWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseSMSWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseSMSWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.serviceTestResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.serviceTest(ESMSV3_1.ServiceReference1.serviceTest request) {
            return base.Channel.serviceTest(request);
        }
        
        public string serviceTest(ESMSV3_1.ServiceReference1.user arg0) {
            ESMSV3_1.ServiceReference1.serviceTest inValue = new ESMSV3_1.ServiceReference1.serviceTest();
            inValue.arg0 = arg0;
            ESMSV3_1.ServiceReference1.serviceTestResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).serviceTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.serviceTestResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.serviceTestAsync(ESMSV3_1.ServiceReference1.serviceTest request) {
            return base.Channel.serviceTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.serviceTestResponse> serviceTestAsync(ESMSV3_1.ServiceReference1.user arg0) {
            ESMSV3_1.ServiceReference1.serviceTest inValue = new ESMSV3_1.ServiceReference1.serviceTest();
            inValue.arg0 = arg0;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).serviceTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.createSessionResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.createSession(ESMSV3_1.ServiceReference1.createSession request) {
            return base.Channel.createSession(request);
        }
        
        public ESMSV3_1.ServiceReference1.session createSession(ESMSV3_1.ServiceReference1.user user) {
            ESMSV3_1.ServiceReference1.createSession inValue = new ESMSV3_1.ServiceReference1.createSession();
            inValue.user = user;
            ESMSV3_1.ServiceReference1.createSessionResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).createSession(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.createSessionResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.createSessionAsync(ESMSV3_1.ServiceReference1.createSession request) {
            return base.Channel.createSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.createSessionResponse> createSessionAsync(ESMSV3_1.ServiceReference1.user user) {
            ESMSV3_1.ServiceReference1.createSession inValue = new ESMSV3_1.ServiceReference1.createSession();
            inValue.user = user;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).createSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.renewSessionResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.renewSession(ESMSV3_1.ServiceReference1.renewSession request) {
            return base.Channel.renewSession(request);
        }
        
        public ESMSV3_1.ServiceReference1.session renewSession(ESMSV3_1.ServiceReference1.session session, out string status) {
            ESMSV3_1.ServiceReference1.renewSession inValue = new ESMSV3_1.ServiceReference1.renewSession();
            inValue.session = session;
            ESMSV3_1.ServiceReference1.renewSessionResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).renewSession(inValue);
            status = retVal.status;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.renewSessionResponse> renewSessionAsync(ESMSV3_1.ServiceReference1.renewSession request) {
            return base.Channel.renewSessionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.closeSessionResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.closeSession(ESMSV3_1.ServiceReference1.closeSession request) {
            return base.Channel.closeSession(request);
        }
        
        public void closeSession(ESMSV3_1.ServiceReference1.session session) {
            ESMSV3_1.ServiceReference1.closeSession inValue = new ESMSV3_1.ServiceReference1.closeSession();
            inValue.session = session;
            ESMSV3_1.ServiceReference1.closeSessionResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).closeSession(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.closeSessionResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.closeSessionAsync(ESMSV3_1.ServiceReference1.closeSession request) {
            return base.Channel.closeSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.closeSessionResponse> closeSessionAsync(ESMSV3_1.ServiceReference1.session session) {
            ESMSV3_1.ServiceReference1.closeSession inValue = new ESMSV3_1.ServiceReference1.closeSession();
            inValue.session = session;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).closeSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.isSessionResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.isSession(ESMSV3_1.ServiceReference1.isSession request) {
            return base.Channel.isSession(request);
        }
        
        public bool isSession(ESMSV3_1.ServiceReference1.session session, out string status) {
            ESMSV3_1.ServiceReference1.isSession inValue = new ESMSV3_1.ServiceReference1.isSession();
            inValue.session = session;
            ESMSV3_1.ServiceReference1.isSessionResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).isSession(inValue);
            status = retVal.status;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.isSessionResponse> isSessionAsync(ESMSV3_1.ServiceReference1.isSession request) {
            return base.Channel.isSessionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.sendMessagesResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendMessages(ESMSV3_1.ServiceReference1.sendMessages request) {
            return base.Channel.sendMessages(request);
        }
        
        public int sendMessages(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessage smsMessage) {
            ESMSV3_1.ServiceReference1.sendMessages inValue = new ESMSV3_1.ServiceReference1.sendMessages();
            inValue.session = session;
            inValue.smsMessage = smsMessage;
            ESMSV3_1.ServiceReference1.sendMessagesResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendMessagesAsync(ESMSV3_1.ServiceReference1.sendMessages request) {
            return base.Channel.sendMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesResponse> sendMessagesAsync(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessage smsMessage) {
            ESMSV3_1.ServiceReference1.sendMessages inValue = new ESMSV3_1.ServiceReference1.sendMessages();
            inValue.session = session;
            inValue.smsMessage = smsMessage;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendMessagesMultiLang(ESMSV3_1.ServiceReference1.sendMessagesMultiLang request) {
            return base.Channel.sendMessagesMultiLang(request);
        }
        
        public int sendMessagesMultiLang(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessageMultiLang smsMessageMultiLang) {
            ESMSV3_1.ServiceReference1.sendMessagesMultiLang inValue = new ESMSV3_1.ServiceReference1.sendMessagesMultiLang();
            inValue.session = session;
            inValue.smsMessageMultiLang = smsMessageMultiLang;
            ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesMultiLang(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendMessagesMultiLangAsync(ESMSV3_1.ServiceReference1.sendMessagesMultiLang request) {
            return base.Channel.sendMessagesMultiLangAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendMessagesMultiLangResponse> sendMessagesMultiLangAsync(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsMessageMultiLang smsMessageMultiLang) {
            ESMSV3_1.ServiceReference1.sendMessagesMultiLang inValue = new ESMSV3_1.ServiceReference1.sendMessagesMultiLang();
            inValue.session = session;
            inValue.smsMessageMultiLang = smsMessageMultiLang;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendMessagesMultiLangAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendCampaignMessages(ESMSV3_1.ServiceReference1.sendCampaignMessages request) {
            return base.Channel.sendCampaignMessages(request);
        }
        
        public int sendCampaignMessages(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsCampaignMessage smsCampaignMessage) {
            ESMSV3_1.ServiceReference1.sendCampaignMessages inValue = new ESMSV3_1.ServiceReference1.sendCampaignMessages();
            inValue.session = session;
            inValue.smsCampaignMessage = smsCampaignMessage;
            ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendCampaignMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.sendCampaignMessagesAsync(ESMSV3_1.ServiceReference1.sendCampaignMessages request) {
            return base.Channel.sendCampaignMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.sendCampaignMessagesResponse> sendCampaignMessagesAsync(ESMSV3_1.ServiceReference1.session session, ESMSV3_1.ServiceReference1.smsCampaignMessage smsCampaignMessage) {
            ESMSV3_1.ServiceReference1.sendCampaignMessages inValue = new ESMSV3_1.ServiceReference1.sendCampaignMessages();
            inValue.session = session;
            inValue.smsCampaignMessage = smsCampaignMessage;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).sendCampaignMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getMessagesFromShortcode(ESMSV3_1.ServiceReference1.getMessagesFromShortcode request) {
            return base.Channel.getMessagesFromShortcode(request);
        }
        
        public ESMSV3_1.ServiceReference1.smsMessage[] getMessagesFromShortcode(ESMSV3_1.ServiceReference1.session session, string shortcode) {
            ESMSV3_1.ServiceReference1.getMessagesFromShortcode inValue = new ESMSV3_1.ServiceReference1.getMessagesFromShortcode();
            inValue.session = session;
            inValue.shortcode = shortcode;
            ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromShortcode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getMessagesFromShortcodeAsync(ESMSV3_1.ServiceReference1.getMessagesFromShortcode request) {
            return base.Channel.getMessagesFromShortcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromShortcodeResponse> getMessagesFromShortcodeAsync(ESMSV3_1.ServiceReference1.session session, string shortcode) {
            ESMSV3_1.ServiceReference1.getMessagesFromShortcode inValue = new ESMSV3_1.ServiceReference1.getMessagesFromShortcode();
            inValue.session = session;
            inValue.shortcode = shortcode;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromShortcodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getMessagesFromLongNumber(ESMSV3_1.ServiceReference1.getMessagesFromLongNumber request) {
            return base.Channel.getMessagesFromLongNumber(request);
        }
        
        public ESMSV3_1.ServiceReference1.smsMessage[] getMessagesFromLongNumber(ESMSV3_1.ServiceReference1.session session, string longNumber) {
            ESMSV3_1.ServiceReference1.getMessagesFromLongNumber inValue = new ESMSV3_1.ServiceReference1.getMessagesFromLongNumber();
            inValue.session = session;
            inValue.longNumber = longNumber;
            ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromLongNumber(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getMessagesFromLongNumberAsync(ESMSV3_1.ServiceReference1.getMessagesFromLongNumber request) {
            return base.Channel.getMessagesFromLongNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getMessagesFromLongNumberResponse> getMessagesFromLongNumberAsync(ESMSV3_1.ServiceReference1.session session, string longNumber) {
            ESMSV3_1.ServiceReference1.getMessagesFromLongNumber inValue = new ESMSV3_1.ServiceReference1.getMessagesFromLongNumber();
            inValue.session = session;
            inValue.longNumber = longNumber;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getMessagesFromLongNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.getSentMessageReportsResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getSentMessageReports(ESMSV3_1.ServiceReference1.getSentMessageReports request) {
            return base.Channel.getSentMessageReports(request);
        }
        
        public ESMSV3_1.ServiceReference1.sentMessages[] getSentMessageReports(ESMSV3_1.ServiceReference1.session session, string startDate, string endDate, string alias) {
            ESMSV3_1.ServiceReference1.getSentMessageReports inValue = new ESMSV3_1.ServiceReference1.getSentMessageReports();
            inValue.session = session;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.alias = alias;
            ESMSV3_1.ServiceReference1.getSentMessageReportsResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getSentMessageReports(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getSentMessageReportsResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getSentMessageReportsAsync(ESMSV3_1.ServiceReference1.getSentMessageReports request) {
            return base.Channel.getSentMessageReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getSentMessageReportsResponse> getSentMessageReportsAsync(ESMSV3_1.ServiceReference1.session session, string startDate, string endDate, string alias) {
            ESMSV3_1.ServiceReference1.getSentMessageReports inValue = new ESMSV3_1.ServiceReference1.getSentMessageReports();
            inValue.session = session;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.alias = alias;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getSentMessageReportsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESMSV3_1.ServiceReference1.getDeliveryReportsResponse ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getDeliveryReports(ESMSV3_1.ServiceReference1.getDeliveryReports request) {
            return base.Channel.getDeliveryReports(request);
        }
        
        public ESMSV3_1.ServiceReference1.smsMessage[] getDeliveryReports(ESMSV3_1.ServiceReference1.session session, string alias) {
            ESMSV3_1.ServiceReference1.getDeliveryReports inValue = new ESMSV3_1.ServiceReference1.getDeliveryReports();
            inValue.session = session;
            inValue.alias = alias;
            ESMSV3_1.ServiceReference1.getDeliveryReportsResponse retVal = ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getDeliveryReports(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getDeliveryReportsResponse> ESMSV3_1.ServiceReference1.EnterpriseSMSWS.getDeliveryReportsAsync(ESMSV3_1.ServiceReference1.getDeliveryReports request) {
            return base.Channel.getDeliveryReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESMSV3_1.ServiceReference1.getDeliveryReportsResponse> getDeliveryReportsAsync(ESMSV3_1.ServiceReference1.session session, string alias) {
            ESMSV3_1.ServiceReference1.getDeliveryReports inValue = new ESMSV3_1.ServiceReference1.getDeliveryReports();
            inValue.session = session;
            inValue.alias = alias;
            return ((ESMSV3_1.ServiceReference1.EnterpriseSMSWS)(this)).getDeliveryReportsAsync(inValue);
        }
    }
}
